canonical/opensearch-operator

.github/workflows/ci.yaml, .gitignore, CONTRIBUTING.md, README.md, actions.yaml, bin/helpers/admin.conf, bin/helpers/root.conf, bin/helpers/root_admin_certs.sh, config.yaml, metadata.yaml, requirements.txt, src/charm.py, templates/jvm.options, templates/opensearch.yml, templates/sysctl.conf, tests/unit/helpers.py, tests/unit/test_charm.py
* Render config templates using jinja2
* self-signed certificates using juju resources
* client relation using elastic search interface
* removed integration-test while snap is not ready
* updated README.md and CONTRIBUTING.md
=> Self-Signed,  Peer and Client Relations

.github/workflows/on_push.yaml, .github/workflows/release.yaml
This PR contains:
- bump of ubuntu version to `22.04`
- removal of dumping log step
=> Fix Github actions 

.github/workflows/ci.yaml, .github/workflows/release.yaml, lib/charms/opensearch/v0/opensearch_tls.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, tests/unit/test_opensearch_tls.py
This PR is about:
- Upgrading the TLS lib
- Incorporate the TLS lib changes in code 
- Fix the impacted unit tests
- Add the `lib-check` action on the github action
The `lib/charms/tls_certificates_interface/v1/tls_certificates.py` file does not require review, as it is the updated lib.
=> TLS lib upgrade

.github/workflows/ci.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/helper_conf_setter.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, pyproject.toml, requirements.txt, src/charm.py, src/opensearch.py, tests/integration/ha/helpers.py, tests/integration/ha/test_horizontal_scaling.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/tls/helpers.py, tests/unit/test_charm.py, tests/unit/test_helper_cluster.py, tests/unit/test_helper_conf_setter.py, tox.ini
This PR requires no review, it's a simple merge to `main` and a version pin of `flake8-docstrings`
=> Feature/scale up: merge to main

.github/workflows/ci.yaml, actions.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_databag.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/rolling_ops/v0/rollingops.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, metadata.yaml, src/charm.py, tests/unit/test_charm.py
This PR requires no review, it's a simple merge of `feature/rolling-ops-integration` into `main`
=> Merge feature/rolling-ops-integration branch into main

lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_config.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_helper_cluster.py, tests/unit/test_opensearch_config.py, tox.ini
This PR requires no review, it is simply merging `feature/role-management` into `main`
=> [DPE-1033] Merge feature/role-management into main

.github/workflows/ci.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/helper_networking.py, lib/charms/opensearch/v0/models.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_exceptions.py, lib/charms/opensearch/v0/opensearch_tls.py, pyproject.toml, requirements.txt, src/charm.py, src/opensearch.py, src/utils.py, tests/integration/ha/helpers.py, tests/integration/helpers.py, tests/unit/test_helper_cluster.py, tests/unit/test_opensearch_base_charm.py, tox.ini
This PR addresses the required helpers part of `safe scale down` feature. 
This PR does not contain:
- [DPE-1321](https://warthogs.atlassian.net/browse/DPE-1321): new roles generation logic
- [DPE-1322](https://warthogs.atlassian.net/browse/DPE-1322): handling of failures when juju leader unit removal 
[DPE-1321]: https://warthogs.atlassian.net/browse/DPE-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1322]: https://warthogs.atlassian.net/browse/DPE-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-880/972] Safe Horizontal scale down - Utility functions and helpers + code cleanup

.github/workflows/ci.yaml, .github/workflows/on_pull_request.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/helper_networking.py, lib/charms/opensearch/v0/models.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_exceptions.py, lib/charms/opensearch/v0/opensearch_tls.py, pyproject.toml, requirements.txt, src/charm.py, src/opensearch.py, src/utils.py, tests/integration/ha/helpers.py, tests/integration/helpers.py, tests/unit/test_helper_cluster.py, tests/unit/test_opensearch_base_charm.py, tox.ini
This PR requires no review. It is simply merging `feature/horizontal-scale-down-utils` into `main`
=> [DPE-880/972] Merge utils / helpers of Safe Horizontal scale down

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/operator_libs_linux/v0/passwd.py, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/operator_libs_linux/v1/systemd.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, metadata.yaml, requirements.txt, src/charm.py, src/opensearch.py, tests/unit/lib/test_helper_charm.py, tests/unit/lib/test_helper_cluster.py, tests/unit/lib/test_helper_databag.py, tests/unit/lib/test_helper_networking.py, tests/unit/lib/test_opensearch_base_charm.py, tests/unit/lib/test_opensearch_config.py, tests/unit/lib/test_opensearch_relation_provider.py, tests/unit/lib/test_opensearch_tls.py, tests/unit/test_charm.py
This PR implements [DPE-1261](https://warthogs.atlassian.net/browse/DPE-1261), namely this PR implements:
- completion of the implementation of the snap based distro for the charm
- minor refactoring of service related methods (start / stop)
- upgrade of:
- python dependencies
- charm libs
- removal of `_create_directories` patches on unit tests.
**Only** review the following (the rest is charm libs upgrades):
- `lib/charms/opensearch/v0/opensearch_distro.py`
- `src/opensearch.py`
- `src/charm.py`
- `metadata.yaml`
- `requirements.txt`
- unit tests (removal of `_create_directories` patches from unit tests)
[DPE-1261]: https://warthogs.atlassian.net/browse/DPE-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added snap install + upgrade libs and deps

.github/workflows/ci.yaml
=> Switch GH on custom runner Ubuntu_4C_16M

tests/integration/helpers.py
This PR fixes a null check condition on the integration tests.
=> Fixed None check

tests/integration/ha/test_ha.py
This PR reorders the provisioning of resources so that it happens in parallel to reduce the waiting time
=> Reduce execution time of multi clusters tests

tests/integration/ha/helpers.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py
This PR increases the retries periods on HTTP requests and fails integration tests when single test fails.
=> Added abort on failed tests + increased timeouts

tests/integration/ha/test_horizontal_scaling.py
This PR fixes the unit counts on an integration test
=> Fix count of units in integration test

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_config.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_keystore.py, lib/charms/opensearch/v0/opensearch_plugin_manager.py, lib/charms/opensearch/v0/opensearch_plugins.py, requirements.txt, src/opensearch.py, tests/conftest.py, tests/unit/lib/test_opensearch_keystore.py, tests/unit/lib/test_plugins.py, tests/unit/resources/test_plugin.properties, tox.ini
This PR requires no review - as it only merges the plugin support feature branch into main
=> [DPE-2347] Model plugin support

.github/workflows/integration.yaml, metadata.yaml, src/opensearch.py
Following snap change: https://github.com/canonical/opensearch-snap/commit/f8353c5caa90a93666a613e7eb64b728eaa1f30a
Update the charm to track this new folder structure.
=> [DPE-2670] Update folder structure to reflect new snap

lib/charms/opensearch/v0/opensearch_distro.py
Removal of unnecessary - too broad retry of (all) commands
=> Remove retry on run_cmd

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/opensearch/v0/opensearch_relation_provider.py, lib/charms/opensearch/v0/opensearch_secrets.py, tests/conftest.py, tests/integration/relations/opensearch_provider/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py, tests/integration/relations/opensearch_provider/application-charm/src/charm.py, tests/integration/relations/opensearch_provider/conftest.py, tests/integration/relations/opensearch_provider/helpers.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py
=> [DPE-1316] external secrets in opensearch (on integration tests stabilization)

.github/workflows/integration.yaml, lib/charms/opensearch/v0/opensearch_base_charm.py, src/alert_rules/prometheus/prometheus_alerts.yaml, src/grafana_dashboards/opensearch.json, tests/integration/ha/test_large_deployments.py
COS logs reporting 
This code has been successfully tested by @phvalguima on a live system.
=> [DPE-3109] logs config

.github/workflows/integration.yaml, lib/charms/opensearch/v0/opensearch_secrets.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py, tests/unit/lib/test_opensearch_secrets.py
This PR extends opensearch_secrets.py to react to new secret-changed behavior in Juju 3.1.7+, as described in [LP#2037120](https://bugs.launchpad.net/juju/+bug/2037120).
=> Add secret fix for 3.1.7

src/alert_rules/prometheus/prometheus_alerts.yaml
This PR updates the alerts in the COS.
* Update yellow alert message
=> [DPE-3346] Review alerts

lib/charms/opensearch/v0/opensearch_base_charm.py
=> [DPE-3700] Add check before scrape is configured

src/opensearch.py, tests/integration/helpers.py, tests/integration/test_charm.py
=> [DPE-3647] Pin snap to rev37 (2.10.0-ubuntu1)

lib/charms/opensearch/v0/opensearch_relation_peer_cluster.py
More details is present on issue #256.
Closes #256.
=> [DPE-4206] _rel_err_data always return True for main orchestrator

lib/charms/opensearch/v0/opensearch_base_charm.py
=> Prevent duplicate peer-relation-changed deferred events

lib/charms/opensearch/v0/opensearch_backups.py
The backup module sets application status on non-leader units, which causes an exception as a non allowed operation.
=> Fix backup status on non-leader units

.github/workflows/ci.yaml, .github/workflows/release.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/tls_certificates_interface/v3/tls_certificates.py
Updates libs and GH workflows to account for the microceph status check fix added in v13.2.
Fixes #301
=> [DPE-4303] Add fix for microceph testing workflow && update libs

.github/workflows/sync_docs.yaml
Sync is failing due to incorrect secret keys.
Updated workflow to match the [expected keys](https://github.com/canonical/data-platform-workflows/blob/ddb4b5112daf309a5665e14caa5dfee03b96eae0/.github/workflows/_sync_docs.yaml#L2-L9)
=> Updated secret keys to match workflow call

README.md
This PR implements [DPE-4726](https://warthogs.atlassian.net/browse/DPE-4726), namely this PR addresses:
- The Readme is outdated and needs improvements
[DPE-4726]: https://warthogs.atlassian.net/browse/DPE-4726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-4726] - Fix readme content

.github/workflows/sync_docs.yaml
Sync docs workflow is failing
Fixed a typo in the pinned workflow version
=> Fix sync_docs workflow
