.github/workflows/release.yaml
This PR contains:
- action to dump logs of release after failure 
- upgrade of checkout v2 to v3
=> Added logs dumping + checkout action upgrade to v3

.github/workflows/ci.yaml, tests/integration/tls/helpers.py
This PR contains: 
- Increase in retry intervals for integration tests that consume HTTP endpoints, to throttle requests
- addition of randomness in the retry waits
=> Increased retry wait in integration tests

.github/workflows/ci.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/helper_conf_setter.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, pyproject.toml, requirements.txt, src/charm.py, src/opensearch.py, tests/integration/ha/helpers.py, tests/integration/ha/test_horizontal_scaling.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/tls/helpers.py, tests/integration/tls/test_tls.py, tests/unit/test_charm.py, tests/unit/test_helper_cluster.py, tests/unit/test_helper_conf_setter.py, tox.ini
This PR addresses [DPE-879](https://warthogs.atlassian.net/browse/DPE-879) and [DPE-881](https://warthogs.atlassian.net/browse/DPE-881) and [DPE-785](https://warthogs.atlassian.net/browse/DPE-785).
Namely, this PR addresses:
- Implementing the scale-up feature on VM charm.
- Integration and unit tests for the scale-up feature on VM charm.
- Removal of the `seed_hosts` property from the config of the cluster manager nodes once cluster bootstrapped.
- minor refactoring on the integration tests.
- Bumped version of OpenSearch to `2.4.0`
The scale up is done automatically through OpenSearch's node discovery mechanism which was implemented on a previous PR.
However, we add the deferral of the node registration and OpenSearch start, until all shards (replicas) of the cluster are in a `STARTED` …
=> Implemented horizontal scale-up

lib/charms/data_platform_libs/v0/data_interfaces.py, metadata.yaml, src/opensearch.py, tests/integration/relations/opensearch_provider/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
This PR contains:
- a retry on the installation of the OpenSearch snap.
- change of location of the config from SNAP_COMMON to SNAP_DATA
- update of the data interfaces lib to incorporate new upstream fixes)
The integration tests will pass once [new snap released](https://github.com/canonical/opensearch-snap/pull/21)
=> Snap install retry and path updates + lib update

.github/workflows/ci.yaml
Currently the CI uses the heavy runner for all tests, meaning the tests all run in series rather than in parallel. Furthermore, not all tests need the heavy runner, so this PR makes use of the light runners where possible, and only uses the heavy runner where necessary
client-relation tests are intermittently failing. These have a fix in a separate PR, and aren't affected by this PR.
=> Updating CI to only use heavy runner when necessary

tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py, tests/integration/ha/test_horizontal_scaling.py, tests/integration/helpers.py, tox.ini
This PR implements [DPE-1262](https://warthogs.atlassian.net/browse/DPE-1262) & [DPE-1265](https://warthogs.atlassian.net/browse/DPE-1265), namely this PR implements:
- continuous writes for the integration tests:
- bulk inserts 
- single doc inserts
- Added the `opensearch-py` client in tests, for hosts rotation when performing requests 
- Updated `operator_libs_linux` libraries
[DPE-1262]: https://warthogs.atlassian.net/browse/DPE-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1265]: https://warthogs.atlassian.net/browse/DPE-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1962] Continuous writing in tests

.github/workflows/ci.yaml, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_health.py, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/operator_libs_linux/v1/systemd.py, lib/charms/rolling_ops/v0/rollingops.py, requirements.txt, src/opensearch.py, tox.ini
This PR fixes some issues that arose by running the `continuous writes` routines:
- during scale up, only recompute the roles once the last unit joins 
- make sure the leader unit's roles can be updated
- for the first unit on the cluster, only wait for the `opensearch service` to start, no need to check the host:port
- better health management
- externalized the health management into separate file/class
- updated charm libs
- Do NOT merge before [this PR](https://github.com/canonical/opensearch-operator/pull/57)
=> Horizontal scaling and status related bug fixes

lib/charms/opensearch/v0/opensearch_base_charm.py, tests/integration/ha/helpers.py, tests/integration/ha/test_horizontal_scaling.py
This PR implements [DPE-1266](https://warthogs.atlassian.net/browse/DPE-1266), namely this PR implements:
- targeted removal of:
- elected cluster manager node 
- elected juju leader node
- externalization of the `app name` for running integration tests against existing running deployments.
[DPE-1266]: https://warthogs.atlassian.net/browse/DPE-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1266] HA test: kill cluster_manager and juju leader nodes 

.github/workflows/ci.yaml, tests/integration/ha/helpers.py, tests/integration/ha/helpers_data.py, tests/integration/ha/test_ha.py, tests/integration/ha/test_horizontal_scaling.py, tests/integration/helpers.py, tox.ini
This PR adds helpers useful and used in HA tests. Namely, this PR adds:
- `helper_data.py`, helper for data related operations
- Shards collection / operations
- added the `ha-integration` in ci and tox.ini
=> Helpers for ha tests

tests/integration/ha/test_horizontal_scaling.py
This PR enriches the test about primary removals:
- Removal of Elected CM node ==> previous PR 
- Removal of Juju leader node ==> previous PR
- **Removal of Node hosting the Primary shard of an index ==> this PR**
=> [DPE-1266] HA test: Added test of primary shard reelection

tests/integration/relations/opensearch_provider/test_opensearch_provider.py
This test is flaky. I've removed the status fast-forwards in an attempt to stabilise it.
=> Remove fast-forwards from scaling test

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_config.py, lib/charms/opensearch/v0/opensearch_distro.py, tests/unit/lib/test_opensearch_config.py
The kill db process HA test raised a bug that occurs for the first unit, which only contains 1 seed_host (itself - since no other node was up in the cluster). If the process on this unit restarts, this node will not be able to join the rest of the cluster as the discovery cannot happen.
- we now update all the nodes with newly joined `cluster_manager` eligible nodes addresses
- to avoid having to restart each node upon newly discovered cluster manager eligible:
- we no longer  rely on `discovery.seed_hosts` as it cannot be changed later without a restart
- we use `discovery.seed_providers: file`
- we use `unicast_hosts.txt` for storing: ips + aliases + hostnames ==> hot reloaded
The Snap was updated with this change
=> Update the seed_hosts regularly 

tests/integration/ha/test_ha.py
This PR implements [DPE-1631](https://warthogs.atlassian.net/browse/DPE-1631), namely this PR implements:
- integration test for killing the opensearch process in the elected `cluster_manager` node
- verify the writes continue
- verify a new cluster manager eligible node got elected 
- verify the previously killed node restarts successfully and joins back the cluster formation
[DPE-1631]: https://warthogs.atlassian.net/browse/DPE-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1631] HA test: kill opensearch process in elected cluster_manager node

tests/integration/ha/test_ha.py
This PR implements [DPE-1632](https://warthogs.atlassian.net/browse/DPE-1632), namely this PR implements:
- integration test for freezing the opensearch process in the elected `cluster_manager` node
- verify the writes continue
- verify a new cluster manager eligible node got elected 
- resume the process
- verify the previously stopped node continues successfully and joins back the cluster formation
[DPE-1632]: https://warthogs.atlassian.net/browse/DPE-1632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1632] HA test: freeze process in elected CM node

tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py, tests/integration/ha/test_ha.py, tests/integration/helpers.py
This PR implements [DPE-1638](https://warthogs.atlassian.net/browse/DPE-1638), namely this PR implements:
- integration test for killing the opensearch process on all the nodes of the cluster - for 3 minutes
- verify the nodes restart automatically after 3 minutes 
- verify the writes continue when the nodes are up 
[DPE-1638]: https://warthogs.atlassian.net/browse/DPE-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1638] - HA tests - full cluster crash

.github/workflows/release.yaml, tests/integration/ha/test_ha.py, tests/integration/helpers.py
This PR implements [DPE-1635](https://warthogs.atlassian.net/browse/DPE-1635) - namely, this PR implements:
- integration test for killing (`SIGTERM`) the opensearch process on all the nodes of the cluster - for 3 minutes
- verify the nodes restart automatically after 3 minutes
- verify the cluster formation is intact
- verify the writes continue when the nodes are up
[DPE-1635]: https://warthogs.atlassian.net/browse/DPE-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1635] - HA tests - Full cluster restart

.github/workflows/ci.yaml, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_relation_provider.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py
When adding a second relation with the same index, we fail to create the index and enter a fail/defer/retry loop. This means the user is never created, so the new relation is never accessible. 
This PR updates the error response check in `call()` to verify that `error_response is None`. This fixes the issue because we were getting false negatives when evaluating `not error_response` in this function, since a failed response is falsy.
=> Fix client integration bug when adding two relations that access the same index

lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_conf_setter.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_config.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_exceptions.py, lib/charms/opensearch/v0/opensearch_tls.py, src/charm.py, tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py, tests/integration/ha/test_ha.py, tests/integration/helpers.py, tests/integration/tls/test_tls.py, tests/unit/lib/test_opensearch_base_charm.py
This PR implements the HA test and fixes the bugs raised with it for [DPE-1557](https://warthogs.atlassian.net/browse/DPE-1557), namely - this PR implements:
- Integration tests for:
- network cut - with IP change - on node with elected CM
- network cut - with IP change - on node with primary shard of index
- helpers for accurately retrieving all units related information
- implementation:
- renewal of certificates for node after the IP change 
- renewal of the `network.host` content with the new hosts
- manual trigger of topology re-computing after network restored
- fixes:
- duplication issue of the content of the `jvm.options` file 
- infinite loop of the opensearch daemon restart
- tls cert key format
- only mark a unit as `ready` when it's fully able to take on requests 
- unit tests …
=> [DPE-1557] - HA tests - network cut - with IP change

lib/charms/opensearch/v0/helper_charm.py, tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py, tests/integration/ha/test_ha.py, tests/integration/helpers.py
This PR implements the HA test and fixes the bugs raised with it for [DPE-1557](https://warthogs.atlassian.net/browse/DPE-1557), namely - this PR implements:
- Integration tests for:
- network cut - without IP change - on node with elected CM
- network cut - without IP change - on node with primary shard of index
- removed pattern matching because charmcraft `2.3` is based on `core20` which comes with `python 3.8` ==> charmcraft fails packing
[DPE-1557]: https://warthogs.atlassian.net/browse/DPE-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-1557] - HA tests - network cut - without IP change

lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/opensearch_relation_provider.py, tests/integration/ha/test_ha.py, tests/integration/helpers.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py, tests/integration/test_charm.py, tests/unit/lib/test_opensearch_relation_provider.py
Previously we weren't making use of the `status.clear()` function to clear the unit status after the relation-created hook fires. This PR fixes that, allowing us to preserve status information.
=> Clearing statuses correctly

.github/workflows/integration-limited-juju3.yaml, .github/workflows/pr.yaml, .github/workflows/pre_integration_checks.yaml, tox.ini
Pipelines are only running tests on Juju3 on PRs.
Partial (essential) set of tests added in a matrix to be also run on Juju3
**Rationale**: These tests are sufficient for secrets testing, and keep a good balance on the pipeline execution time.
**NOTE**: The different set of tests was the reason for the "copy-paste" instead of a simple matrix.
**NOTE2**: `h-scaling-integation` failures are global to the repository, unrelated to changes presented here.
=> [DPE-1817] Github workflows adopted for Juju 3 testing (limited set of tests)

.github/workflows/release.yaml
Release pipeline was missing to pass a value for the LIBJUJU_VERSION_SPECIFIER variable for unittests (that need to know what version of Juju is running, since divergences on Juju3 feature: Secrets)
Passing the missing info on the Release pipeline
Tested on this pipeline: https://github.com/canonical/opensearch-operator/actions/runs/6048563873
=> [Fix] Fix missing env variable on release pipeline 

src/opensearch.py
Commit: https://github.com/canonical/opensearch-snap/commit/e9964ef7b8c41df8bdd193bc126b3ff3a2a21065
In opensearch-snap added a dependency to snapd 2.60, otherwise installing opensearch snap fails with permission denied to /dev/shm/performance-analyzer.
However, not all deployments will start at this version and should be refreshed before installation can proceed.
Resolves issue: https://github.com/canonical/opensearch-operator/issues/119
=> [DPE-2589] OpenSearchSnap refreshes snapd before installation

lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_relation_provider.py, lib/charms/opensearch/v0/opensearch_users.py, tests/integration/relations/opensearch_provider/test_opensearch_provider.py
This PR fixes bugs causing intermittent failures on CI:
- some missing exception handling on the client relations - namely non caught http errors
- referring to a non existing variable on the `e.status_code`
- usage of status.set from the user relations, to avoid overriding the model last active since status
- increase timeout to 60s (from 25s) on `_run_cmd` 
- added retry on `_run_cmd`
=> Fixed error handling in client integration

lib/charms/opensearch/v0/opensearch_distro.py, src/opensearch.py
The new version of the snap relies on the jdk of the snap environment instead of the one bundled by OpenSearch.
This PR replaces the path of the JDK by the correct one
=> Fixed jdk path

actions.yaml, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_backups.py, tests/integration/ha/test_backups.py, tests/unit/lib/test_backups.py
Extends https://github.com/canonical/opensearch-operator/pull/135 and adds restore support.
This PR will roll the cluster's indices back to the snapshot and override any conflicting index.
It tests two scenarios:
1) Snapshot / restore in the same cluster
2) Snapshot / redeploy cluster / restore
=> [DPE-2345][DPE-2451] restore action

.github/workflows/integration.yaml, actions.yaml, lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_backups.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_plugin_manager.py, tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py, tests/integration/ha/helpers_data.py, tests/integration/ha/test_backups.py, tests/unit/lib/test_backups.py, tests/unit/lib/test_opensearch_base_charm.py
[DPE-3243](https://warthogs.atlassian.net/browse/DPE-3243): list-backups now contains only relevant information, in this case the backup-id and its status; the PR removes the "backup-type" column, as it has no meaning in OpenSearch
[DPE-3246](https://warthogs.atlassian.net/browse/DPE-3246): backups will be async and restores will be synchronous. Users can follow the restore in the juju status. In any case, the indices that are being restored will be closed, so the user needs to wait.
[DPE-3243]: https://warthogs.atlassian.net/browse/DPE-3243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-3246]: https://warthogs.atlassian.net/browse/DPE-3246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> [DPE-3243][DPE-3246] Finishes the backup with fully async restore

.github/workflows/integration.yaml
This PR implements [DPE-3568](https://warthogs.atlassian.net/browse/DPE-3568), namely this PR removes the GH enterprise runner.
[DPE-3568]: https://warthogs.atlassian.net/browse/DPE-3568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-3568] Remove the large github runner

lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/opensearch_backups.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_plugin_manager.py, lib/charms/opensearch/v0/opensearch_plugins.py, tests/integration/ha/test_backups.py, tests/unit/lib/test_backups.py, tests/unit/lib/test_ml_plugins.py, tests/unit/lib/test_plugins.py
Move the status messages in `opensearch_backup` module to comply with `charm.status.{set,clear}`. All text has been moved to `constant_charms.py`.
This PR also simplifies the exception structure, where the plugins should log their own errors if that is not supposed to come back to the plugin manager and the charm itself. The exception `OpenSearchPluginClusterNotReadyError` has been abandoned in favor of the default exception for the same type of error in `constant_exceptions`.
Tests have been updated accordingly.
=> [DPE-3578] clear backup status

lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_backups.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_plugin_manager.py, lib/charms/opensearch/v0/opensearch_plugins.py, lib/charms/opensearch/v0/opensearch_relation_provider.py, tests/integration/ha/test_large_deployments.py, tests/integration/plugins/test_plugins.py, tests/unit/lib/test_backups.py, tests/unit/lib/test_helper_cluster.py, tests/unit/lib/test_ml_plugins.py, tests/unit/lib/test_plugins.py
Adds a GET /_cluster/settings, which returns the configuration of the cluster at the moment, including defaults. This way, plugins can check if they should add their configs and request a restart during the start cycle of the charm.
The `_is_enabled` is also extended to use the cluster settings instead of checking the configuration files directly. 
Moved `OpenSearchPluginConfig` to extend `pydantic.BaseModel`. It ensures that configuration is translated to `Dict[str, str]`, in special the boolean value, that must have a format of: `true` or `false`.
Also closes [DPE-3579](https://warthogs.atlassian.net/browse/DPE-3579): move the plugin settings status to use the charm's `status.{set,clear}` APIs.
[DPE-3579]: https://warthogs.atlassian.net/browse/DPE-3579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> [DPE-3573][DPE-3579] Fix #164 - check _cluster/settings instead of opensearch.yml for plugins

lib/charms/opensearch/v0/constants_charm.py, src/opensearch.py, tests/integration/helpers.py, tests/integration/test_charm.py
Pins the charm to snap v2.11.1. Also, moves the snap revision constant to a lib, so both src/opensearch.py and integration tests can access the same value.
=> [DPE-3647] Pin charm to snap v2.11.1

actions.yaml, lib/charms/opensearch/v0/opensearch_backups.py, tests/integration/ha/helpers.py, tests/integration/ha/helpers_data.py, tests/integration/ha/test_backups.py
Re adds the backup testing infra + AWS testing for backup, as described in [DPE-3660](https://warthogs.atlassian.net/browse/DPE-3660), on top of the new CI testing infra.
It is broken in two types of tests:
1. Per cloud test: backup, restore, relation removal/readd, disaster recovery
2. All clouds: test configuration changes and backup / restore, test expected API call responses
The tests will use different groups, so they can run in parallel.
[DPE-3660]: https://warthogs.atlassian.net/browse/DPE-3660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-3660] Add backups testing infra

lib/charms/opensearch/v0/opensearch_base_charm.py
Currently, whenever the plugin manager is executed, there is an update of the status in both app and unit level. This PR changes the behavior, and only the app level should be updated from now on.
=> Plugin manager should update app level status

lib/charms/opensearch/v0/opensearch_backups.py, tests/integration/ha/test_backups.py
Updates the backup lib to consider the new error handling with `OpenSearchHttpError` and `request()` method.
Also removes a lingering "MaintenanceStatus" if we have a configuration error in the backups.
=> [Backup] Add error handling to _request

tests/unit/lib/test_opensearch_tls.py
There was a recent update on the ops framework and it now explicitly checks for the `_TestModelBackend.networks` for networks set. If no networks are set, it will "create" one: `192.0.2.0`.
This PR adds the network 1.1.1.1 to resolve this issue in the TLS.
Closes #250
=> [DPE-4192] Update test_opensearch_tls

lib/charms/opensearch/v0/opensearch_base_charm.py
When starting opensearch, port 9200 was not shown as open port in `juju status` or `juju show-unit`, as described in https://github.com/canonical/opensearch-operator/issues/104
After startup of opensearch was completed, `self.unit.open_port`is called to set tcp port 9200 as open for the unit.
It is now displayed in `juju status`:
```
Model       Controller  Cloud/Region         Version  SLA          Timestamp
opensearch  opensearch  localhost/localhost  3.1.8    unsupported  09:24:11Z
App                        Version  Status  Scale  Charm                      Channel  Rev  Exposed  Message
opensearch                          active      1  opensearch                            7  no       
tls-certificates-operator           active      1  tls-certificates-operator  stable    22  no …
```
=> DPE-2333 show open ports

lib/charms/opensearch/v0/helper_charm.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_peer_clusters.py, lib/charms/opensearch/v0/opensearch_relation_peer_cluster.py
We should replace calls to `relation_{joined,changed}.emit()` by their end-method's handler. Otherwise we will face situations like #265, where a deferred event constantly gets called up, generates new events which also get deferred and end in a snow ball of deferrals.
Closes #265
=> [DPE-4224] Remove relation_{joined,changed}.emit() calls

lib/charms/opensearch/v0/models.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_relation_peer_cluster.py, tests/integration/ha/continuous_writes.py, tests/integration/ha/helpers.py
This PR implements [DPE-4281](https://warthogs.atlassian.net/browse/DPE-4281). Namely, this PR implements various fixes for Multiple issues arose from secrets which led to endless triggers of secrets-changed hook - became more obvious on large deployments.
- Ensure that COSUser is NOT updated constantly on post_start_init
- Correct setting / deletion of started flag in the start_opensearch workflow 
- correct settings of s3 credentials in large deployments relations and preventing empty values to be set on:
- both sides of the peer-cluster relation
- peer relation
- In addition to AdminUser propagate in large deployment relations: 
- COSuser 
- Kibanaserver
- fix status clearing from requirer side of large deployment relation
- make continuous writes more robust
[DPE-4281]: …
=> [DPE-4281] - Fixed secrets updates + users/s3 handling on large-depl. relations 

tests/integration/ha/test_backups.py, tests/integration/plugins/test_plugins.py
Two main fixes post latest large deployments updates:
* DPE-4285: fix the backups for large deployments
* Ensure the enable/disable KNN tests in `test_plugins.py` will have all its restarts resolved at the end of the test itself
=> [DPE-4285] Fix Backup Large Deployments CI

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_peer_clusters.py
When the peer cluster relation is completely healthy at once, we should ensure that error messages previously applied from outside the relation have also been cleared.
=> Apply missing status clearing

lib/charms/opensearch/v0/opensearch_locking.py
https://github.com/canonical/opensearch-operator/issues/309
Also release stale locks in the opensearch database from units no longer existing when releasing the lock a unit is currently holding.
=> [DPE-4421] Release stale node locks

tests/integration/ha/test_backups.py, tests/integration/test_charm.py
https://github.com/canonical/opensearch-operator/issues/243
The issue itself could not be reproduced with the current main branch (revision 95 in channel 2/edge). It was presumably fixed with https://github.com/canonical/opensearch-operator/pull/312. This PR adds integration test coverage.
=> [DPE-4130] Remove workarounds for removing the OpenSearch application

lib/charms/opensearch/v0/opensearch_tls.py, tests/unit/lib/test_opensearch_tls.py
https://github.com/canonical/opensearch-operator/issues/204
- implement handler for the `on.certificate_invalidated` event
- request new certificate for the invalidated one
- add unit test coverage in `tests/unit/lib/test_opensearch_tls.py:test_on_certificate_invalidated`
=> [DPE-3822] handle invalidated certificates

lib/charms/opensearch/v0/opensearch_base_charm.py
https://github.com/canonical/opensearch-operator/issues/320
When the last unit in a cluster is stopping, it adds the `voting_config_exclusion`, but doesn't delete it anymore (because all units are already stopped). It is then persisting on disk. If the storage is reused and the first new unit starts, it may happen that the new unit can't become cluster manager because it's not possible to reach quorum.
Therefore the last unit stopping should not add a voting exclusion.
=> [DPE-4557] fix timeout when initializing the security index

lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/opensearch_base_charm.py, src/grafana_dashboards/opensearch.json, tests/integration/plugins/test_plugins.py, tests/integration/relations/helpers.py, tests/unit/lib/test_backups.py
Renames our dashboard to "Charmed OpenSearch". This PR addresses the following needs in our COS integration for large deployments:
1) **Fixes data node integration with COS**: COSAgentProvider was not tracking peer-cluster-* events, which means it was not receiving changes done to the COSUser by the main orchestrator
2) **Add integration tests to COS**: large deployments integration tests for COS were missing, this PR makes `test_plugins` more flexible, so it can run both small and large deployments
3) **Manage user passwords**: large deployments will now answer to `set-password` action and `MAIN_ORCHESTRATOR` propagates the new password value down to the other apps
4) **Adds Role to Dashboard**: adds "Roles" as a dropdown option to Grafana dashboard, allowing to filter each cluster also …
=> [DPE-4553][DPE-4208][DPE-3970] Extend large deployments to test_plugins.py &&  Fix dashboards

lib/charms/opensearch/v0/constants_charm.py
New snap version 53 adds support for hugepages read on sysfs. This charm bumps the snap version so we can start using it on the charm deployments.
=> [DPE-4769] Add hardware-observe support

lib/charms/opensearch/v0/opensearch_tls.py, tests/unit/lib/test_opensearch_tls.py
If the `on_certificate_available` hook is run before the `on_relation_created` (for the TLS relation), it may happen that the keystore password is not yet available and the creation of keystore or truststore fails (as seen in [this](https://github.com/canonical/opensearch-operator/actions/runs/9853942720/job/27205887472) integration test run).
Create the keystore password also on the actions triggered by `on_certificate_available`, namely when the ca is stored or when the TLS certs are stored.
=> [DPE-4654] create keystore password if not exists

lib/charms/opensearch/v0/helper_charm.py, lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_tls.py, tests/unit/lib/test_helper_charm.py
To avoid writing sensitive information to the logs I propose to adjust the run_cmd function and mask known patterns for passwords and secrets.
=> [DPE-4654] do not log command args

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_tls.py, tests/unit/lib/test_opensearch_tls.py, tests/unit/test_charm.py
Currently the secrets for storing the truststore and keystore passwords are named `keystore-password-{category}`, which is not ideal considering they are already stored as part of the tls secret for each category.
Rename the secrets to:
- `truststore-password` for the ca truststore
- `keystore-password` as the generic name that can be referenced within the respective secrets app-admin, unit-transport and unit-http
=> [DPE-4857] improve naming of truststore and keystore secrets

lib/charms/opensearch/v0/opensearch_config.py
The way `publish_host` is being dealt, it is expected a list of hostnames / IPs. However, publish_host has a single value. Hence, we should not filter it with `set()`.
This fix has been originally applied in this PR: https://github.com/canonical/opensearch-operator/pull/367. It has been also verified with successful passed runs of `test_ha_networking.py` checks, which triggers this logic.
=> `publish_host` is a single IP, not a list

charmcraft.yaml
With the latest version 3.1.1 of charmcraft, build and deploying charms fails if there is a prime part in the `charmcraft.yaml` file: `Warning: use of 'prime' in a charm part is deprecated and no longer works, see https://juju.is/docs/sdk/include-extra-files-in-a-charm`.
Fix the charmcraft.yaml config file.
=> Fix to support charmcraft 3.1.1

tests/integration/plugins/test_plugins.py
We should run actions against `MAIN_ORCHESTRATOR` when managing passwords, which we are not completely doing in our `test_plugins` CI run.
=> Use `app` instead of `APP_NAME` for large deployments

lib/charms/opensearch/v0/constants_charm.py
Updates the snap pinning to consider the newer revision with 2.14.0-ubuntu1. This release contains the backported fixes for plugin MLCommons.
=> [DPE-5047] Backport MLCommons changes

poetry.lock, pyproject.toml
The `ha/test_storage.py` started failing due to newer libjuju. Downgrading to 3.4 as we are currently using juju 3.4.x for CI.
Closes #388
=> [DPE-5093] Downgrade juju dependency to 3.4.0.0

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_health.py
This PR addresses the issues https://github.com/canonical/opensearch-operator/issues/327 and https://github.com/canonical/opensearch-operator/issues/324.
When Opensearch is in the process of shutting down, the operator currently does not wait for data to be moved away from the stopping unit. This may result in shards not being assigned and could cause loss of data. In cases where the index `.charm_node_lock` is impacted, the operator can no longer acquire the lock to start or stop Opensearch. This will result in `503` errors in the logfile.
The behavior can be seen in this CI run, with some additional logging information added for debugging: https://github.com/canonical/opensearch-operator/actions/runs/10269420444/job/28415611890?pr=387
```
Shards before relocation: [...{'index': …
```
=> [DPE-4931] fix locking with unassigned shards

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_health.py, lib/charms/opensearch/v0/opensearch_nodes_exclusions.py
When an Opensearch node is restarted by the operator, currently the shards assigned to this node are first moved away from the node, and after restarting moved back. This is a lot of work that, in case of simple restarts, is not necessary.
To avoid this behavior, no allocation exclusion should be added for the departing node, when a restart operation is performed.
Check for the `restart` flag in `_stop_opensearch()` and pass it through to `opensearch_exclusions.add_current()`. If set to `True`, only the voting exclusion should be added for the departing node, but no allocation exclusion.
=> [DPE-4935] no allocation exclusions on restart

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_tls.py
In cases where reloading TLS certs via API fails, Opensearch should be restarted to pick up the new certs. This could happen e.g. after a network cut, if the API is not available and new TLS certs have been requested because of a new IP address.
This can be seen [in the current failures](https://github.com/canonical/opensearch-operator/actions/runs/10361988050/job/28683584556#step:27:5111) of the integration test `test_ha_networking.py`.
If an error occurs when reloading the certs, restart Opensearch to pick up the new certificates.
=> make TLS certs reload more robust

charmcraft.yaml
I'd like to standardize the approach across data platform repos so that future automated tooling that may need to use this can be shared across all our repos
PRs in other repos:
https://github.com/canonical/mysql-operator/pull/496
https://github.com/canonical/mysql-router-k8s-operator/pull/298#discussion_r1713906228
https://github.com/canonical/mongodb-operator/pull/455
=> Standardize prime plugin in charmcraft.yaml

lib/charms/opensearch/v0/opensearch_distro.py, lib/charms/opensearch/v0/opensearch_relation_provider.py
This PR implements [DPE-4875](https://warthogs.atlassian.net/browse/DPE-4875), namely:
- check sysctl requirements 
- apply them if needed and possible
- check them again for verification
[DPE-4875]: https://warthogs.atlassian.net/browse/DPE-4875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-4875] Apply sysctl requirements if possible

lib/charms/opensearch/v0/opensearch_base_charm.py
The unicast_hosts.txt needs to be also reviewed at `update-status`, so we can consider situations such as nodes that have been broken and not responsive anymore.
=> [DPE-5169] Add unicast_hosts.txt review on update_status

.github/workflows/sync_docs.yaml, lib/charms/opensearch/v0/opensearch_tls.py, tests/integration/tls/test_tls.py
This PR provides integration test coverage for the workflow of expiring TLS certificates and their renewal. 
It also includes a bugfix for renewing the expiring certificates, or better creating the certificate signing requests: When initially creating them, they do not include `unique-id` in the subject. But on renewal this is included, which causes the `subject` of the renewed certificate to be different from the initial one.
In addition to that, there's a config change to `TLSCertificatesRequiresV3` in order to get notification for expiring certificates with a reasonable lead time.
Please also note the documentation added for the TLS certificates workflow here: https://github.com/canonical/opensearch-operator/wiki/TLS-certificates-workflow
=> [DPE-4653] certificate expiration integration test

tests/integration/tls/test_tls.py
With https://github.com/canonical/opensearch-operator/pull/408 a new integration test was introduced, asserting that the workflow for certificate expiration (and renewal) is functional. The test includes waiting for about 1 hour for receiving a secret expiry from `juju` and for `certificate availabe` events from the self-signed-certificates operator. Obviously the waiting time is not long enough, as the logs and history of events processed in [this CI run](https://github.com/canonical/opensearch-operator/actions/runs/10558606898/job/29252649331) shows, where the certificates operator did not yet send `CertificateAvailableEvents` after the secrets for the current ones have expired.
Increase the fixed waiting time to cover at least on processing of `update_status` on the certificates …
=> increase waiting time for certificate expiry

tests/integration/tls/helpers_manual_tls.py, tests/integration/tls/test_manual_tls.py, tests/integration/tls/test_tls.py
Add a test for an OpenSearch deployment with TLS certificates issued by the `manual-tls-certificates` operator.
=> [DPE-5202] Test TLS through Manual TLS Certificates

tests/integration/tls/test_tls.py
- The current TLS expiration time in the tls_expiration test is long.
- Edit the deployed unit of OpenSearch to have a smaller secret expiry time thus triggering a TLS rotation early.
=> [DPE-5408] Reduce test tls expiration time

lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_config.py, lib/charms/opensearch/v0/opensearch_tls.py, tests/integration/ha/test_large_deployments_relations.py, tests/integration/ha/test_roles_managements.py, tests/unit/helpers.py, tests/unit/lib/test_opensearch_tls.py
This PR implements [DPE-5402](https://warthogs.atlassian.net/browse/DPE-5402) - namely this PR fixes:
- setting a wrong role `coordinating_only`
- not setting `node.roles: []` when only the `coordinating` role was set
- This PR also prevents the TLS the workflow to start on non-main orchestrator when the current cluster was **not a consumer** (which would create a mismatch in the APP_ADMIN tls values). 
[DPE-5402]: https://warthogs.atlassian.net/browse/DPE-5402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DPE-5402] Fix wrong roles setting of "coordinating" node

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sync_docs.yaml, poetry.lock, pyproject.toml
Shared workflows (from data-platform-workflows) were outdated at `v16.7.0`. This prevented the repo from using newer shared workflows, like [`sync_docs.yaml`](https://github.com/canonical/data-platform-workflows/blob/main/.github/workflows/sync_docs.md). 
* Updated existing workflow versions to `v21.0.1` (latest)
* Updated `sync_docs.yaml` to new version and new workflow parameters
* Updated `poetry.lock` version and commit hash
* [breaking: Change default charmcraft version to 2.x](https://github.com/canonical/data-platform-workflows/commit/da8bb57d6a9650fef8683cb76f233cd672f63db5)
* [breaking(`integration_test_charm.yaml`): Remove `jhack tail` logs](https://github.com/canonical/data-platform-workflows/commit/37129f44b9dacb57c67ed2ebbbc9fbfa3d218de5)
* …
=> Update workflows to v21.0.1

lib/charms/opensearch/v0/opensearch_distro.py
This PR increases the max allowed for swappiness and fixes an erroneous string to string comparison 
Manually tested on: AWS EC2
=> Increase swappiness max and fix cast

lib/charms/opensearch/v0/constants_charm.py, lib/charms/opensearch/v0/helper_cluster.py, lib/charms/opensearch/v0/opensearch_distro.py, tests/unit/helpers.py, tests/unit/lib/test_backups.py, tests/unit/lib/test_helper_cluster.py, tests/unit/lib/test_opensearch_config.py, tests/unit/lib/test_opensearch_distro.py, tests/unit/lib/test_opensearch_lock.py, tests/unit/resources/config/opensearch.yml
https://github.com/canonical/opensearch-operator/issues/222
Context (as highlighted in the [issue comment](https://github.com/canonical/opensearch-operator/issues/222#issuecomment-2306491781)):
"When a unit is online, unit-specific service information is taken from the Opensearch API (`/_nodes`).
However if the unit is offline, we fall back to static configuration.
This is the part where we had the issue, in case `node.roles` was missing from the configuration."
We shouldn't directly refer to a field that may be missing from the config.
NOTE: Since the `opensearch_distro` had no unittests, this PR is also adding a new unttest module dedicated to `opensearch_distro`. For the time being only the concerned `current()` method is being tested (both for happy and broken path -- the latter was …
=> [DPE-4049][BUGFIX] Exception when offline unit is missing `node.roles` from static config

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_relation_peer_cluster.py
We used to include nodes in the bootstrapping process only based on the `cluster_manager` role. 
We should instead only do it on the `MAIN_ORCHESTRATOR` and flag for every subsequent non-MAIN-ORCHESTRATOR that the cluster is already bootstrapped and that there is no need to attempt that again.
=> Exclude subsequent CM clusters from bootstrap

lib/charms/tls_certificates_interface/v3/tls_certificates.py
The `tls_certificates.py` lib released a new version with minor formatting / comment fixes. Updates opensearch to use that new version instead.
=> Add minor fixes from tls cert lib

lib/charms/opensearch/v0/helper_http.py, lib/charms/opensearch/v0/opensearch_distro.py
Currently, the "retrial" mechanism of the `request()` method always target the very same unit, even if we specified more than one option. 
This PR applies the retrial to the different targets of the list.
=> [DPE-5483] Shuffle URLs we try to connect to

lib/charms/opensearch/v0/opensearch_base_charm.py, lib/charms/opensearch/v0/opensearch_tls.py, tests/integration/tls/test_ca_rotation.py, tests/unit/lib/test_opensearch_tls.py
This PR addresses the stabilization of the CA rotation workflow.
The following issues are fixed:
1) Error with `No cert in -in file '/tmp/tmp1uvvhlyo.cert' matches private key [xxx] certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:405:`: The private key was regenerated on every admin certificate request. When a CA rotation is restarting the nodes, the certificate that was being loaded was generated using an old private key and can no longer be validated with the stored key (see https://github.com/canonical/opensearch-operator/issues/417).
2) A long delay when restarting after renewing the TLS certificates on CA rotation (see https://github.com/canonical/opensearch-operator/issues/417).
3) An issue with the CA truststore file being updated/cleaned …
=> [DPE-5283] stabilization for CA rotation and integration test for large deployments

lib/charms/opensearch/v0/helper_http.py, lib/charms/opensearch/v0/helper_networking.py
Currently, each call to `OpenSearchDistribution.requests()` or `OpenSearchCharm.alt_hosts` may generate a number of `ERROR` entries in the charm log. However, these are checks or attempts executed within the each of the routines and not necessarily represent an error of the whole process.
This PR reduces their log to `DEBUG` level instead.
=> [DPE-5483] Update logging on `requests()`code path

tests/integration/upgrades/helpers.py, tests/integration/upgrades/test_small_deployment_upgrades.py
Currently, our CI is failing intermittently whenever we call `juju refresh`, [as the controller is still busy downloading the charm](https://github.com/juju/juju/blob/4584c53183a1b128ce0ffbe5f4e3c4b6235290bc/cmd/juju/application/refresh.go#L371)
To avoid failing due to this intermittent error, we add a retry loop at refresh call.
Closes #454
=> [DPE-5536][test_upgrades.py] CI - Gracefully fail refresh cmd error

lib/charms/opensearch/v0/opensearch_base_charm.py
Due to [LP#2076599](https://bugs.launchpad.net/juju/+bug/2076599)
The  relation databags may be empty if we are running a single unit cluster and we hit "remove-application".
In this case, if we had a post start running, then this method will fail as it tries to check for the deployment description.
Closes #444
=> [DPE-5468][test_charm.py] ensure deployment_desc available at post start
